apiVersion: oam.coding.net/v1alpha2
kind: ComponentDefinition
metadata:
  name: DeploymentTemplateV2
spec:
  available: true
  customVariables:
  - description: 参数
    name: 参数
    param1: STRING
    required: false
    type: ARRAY
    variable: args
  - description: 容器的镜像
    name: 镜像
    required: true
    type: IMAGE
    variable: image
  - description: 端口号
    name: 端口号
    param1: '1'
    param2: '65535'
    required: true
    type: INT
    variable: port
  - description: 副本数
    name: 副本数
    required: false
    type: INT
    variable: replicas
  - description: 服务名称
    name: 服务名称
    param1: '1'
    param2: '64'
    required: true
    type: STRING
    variable: name
  - description: 启动命令
    name: 启动命令
    required: false
    type: STRING
    variable: cmd
  description: 系统内置的Deployment服务模板V2
  service:
    kube:
      template: |-
        apiVersion: v1
        kind: Service
        metadata:
          name: {{.name}}
        spec:
          selector:
            app: {{.name}}
          ports:
          - name: http
            port: {{.port}}
            protocol: TCP
            targetPort: {{.port}}
          type: ClusterIP
  serviceTemplate:
    createTime: 2024-08-17T09:57:40.980Z
    creatorId: 9152296
    description: 系统内置的Deployment服务模板V2
    id: 386067941463080
    name: 内置的Deployment服务模板V2
    seq: DeploymentTemplateV2
    status: ENABLE
    teamId: 4211598
    type: SERVICE
    updateTime: 2024-08-17T09:57:40.980Z
  type: SERVICE
  workload:
    kube:
      template: |-
        apiVersion: apps/v1
        kind: Deployment
        metadata:
          name: {{.name}}
          annotations:
            reloader.stakater.com/auto: "true"
        spec:
          {{- if .replicas }}
          replicas: {{ .replicas }}
          {{- end }}
          selector:
            matchLabels:
              app: {{.name}}
          strategy:
            type: RollingUpdate
            rollingUpdate:
              maxUnavailable: 25%
              maxSurge: 25%
          template:
            metadata:
              labels:
                app: {{.name}}
            spec:
              containers:
              - name: {{.name}}
                image: {{ .image }}
                imagePullPolicy: IfNotPresent
                {{- if .cmd }}
                cmd: {{ .cmd }}
                {{- end }}
                {{- if .args }}
                args: {{ .args }}
                {{- end }}
                ports:
                - containerPort: {{.port}}
