/// <reference types='./globals.d.ts' />
/* tslint:disable */
/* eslint-disable */
/**
 * 接口文档 - version 1.0
 *
 *
 *
 * OpenAPI version: 3.0.0
 *
 * Contact:
 *
 * NOTE: This file is auto generated by the alova's vscode plugin.
 *
 * https://alova.js.org/devtools/vscode
 *
 * **Do not edit the file manually.**
 */
export default {
  'wxMpController.checkUsingGET': ['GET', '/api/'],
  'wxMpController.receiveMessageUsingPOST': ['POST', '/api/'],
  'audioFileController.addAudioFileUsingPOST': ['POST', '/api/audio_file/add'],
  'audioFileController.deleteAudioFileUsingPOST': ['POST', '/api/audio_file/delete'],
  'audioFileController.getAudioFileVOByIdUsingGET': ['GET', '/api/audio_file/get/vo'],
  'audioFileController.listAudioFileByPageUsingPOST': ['POST', '/api/audio_file/list/page'],
  'audioFileController.listAudioFileVOByPageUsingPOST': ['POST', '/api/audio_file/list/page/vo'],
  'audioFileController.searchAudioFileUsingPOST': ['POST', '/api/audio_file/search'],
  'audioFileController.synthesizeUsingPOST': ['POST', '/api/audio_file/synthesize'],
  'audioFileController.uploadAudioFileUsingPOST': ['POST', '/api/audio_file/upload'],
  'categoryController.addCategoryUsingPOST': ['POST', '/api/category/add'],
  'categoryController.deleteCategoryUsingPOST': ['POST', '/api/category/delete'],
  'categoryController.listCategoryByPageUsingPOST': ['POST', '/api/category/list/page'],
  'categoryController.selectOneUsingGET': ['GET', '/api/category/selectOne'],
  'categoryController.updateCategoryUsingPOST': ['POST', '/api/category/update'],
  'dictionaryCategoryController.getDictionaryCategoryByDictionaryIdUsingGET': [
    'GET',
    '/api/dictionary_category/relative'
  ],
  'dictionaryCategoryController.relativeDictionaryCategoryUsingPOST': ['POST', '/api/dictionary_category/relative'],
  'DictionaryWord.addDictionaryWordUsingPOST': ['POST', '/api/dictionary_word/add'],
  'DictionaryWord.addDictionaryWordBatchUsingPOST': ['POST', '/api/dictionary_word/add/batch'],
  'DictionaryWord.deleteDictionaryWordUsingPOST': ['POST', '/api/dictionary_word/delete'],
  'DictionaryWord.getDictionaryWordVOByIdUsingGET': ['GET', '/api/dictionary_word/get/vo'],
  'DictionaryWord.listDictionaryWordBatchUsingPOST': ['POST', '/api/dictionary_word/list/batch'],
  'DictionaryWord.listDictionaryWordByPageUsingPOST': ['POST', '/api/dictionary_word/list/page'],
  'DictionaryWord.listDictionaryWordVOByPageUsingPOST': ['POST', '/api/dictionary_word/list/page/vo'],
  'englishDictionaryController.addEnglishDictionaryUsingPOST': ['POST', '/api/english_dictionary/add'],
  'englishDictionaryController.deleteEnglishDictionaryUsingPOST': ['POST', '/api/english_dictionary/delete'],
  'englishDictionaryController.getEnglishDictionaryVOByIdUsingGET': ['GET', '/api/english_dictionary/get/vo'],
  'englishDictionaryController.importEnglishDictionaryUsingPOST': ['POST', '/api/english_dictionary/import'],
  'englishDictionaryController.listEnglishDictionaryUsingGET': ['GET', '/api/english_dictionary/list'],
  'englishDictionaryController.listEnglishDictionaryByPageUsingPOST': ['POST', '/api/english_dictionary/list/page'],
  'englishDictionaryController.listEnglishDictionaryVOByPageUsingPOST': [
    'POST',
    '/api/english_dictionary/list/page/vo'
  ],
  'englishDictionaryController.listMyEnglishDictionaryVOByPageUsingPOST': [
    'POST',
    '/api/english_dictionary/my/list/page/vo'
  ],
  'englishDictionaryController.updateEnglishDictionaryUsingPOST': ['POST', '/api/english_dictionary/update'],
  'EnglishWords.addEnglishWordUsingPOST': ['POST', '/api/english_word/add'],
  'EnglishWords.addEnglishWordBatchUsingPOST': ['POST', '/api/english_word/add/batch'],
  'EnglishWords.deleteEnglishWordUsingPOST': ['POST', '/api/english_word/delete'],
  'EnglishWords.getEnglishWordDetailUsingGET': ['GET', '/api/english_word/detail'],
  'EnglishWords.getDuplicateWordsUsingGET': ['GET', '/api/english_word/duplicates'],
  'EnglishWords.getEnglishWordBatchUsingPOST': ['POST', '/api/english_word/get/batch'],
  'EnglishWords.getEnglishWordVOByIdUsingGET': ['GET', '/api/english_word/get/vo'],
  'EnglishWords.listEnglishWordByPageUsingPOST_1': ['POST', '/api/english_word/list/page'],
  'EnglishWords.listEnglishWordByPageUsingPOST': ['POST', '/api/english_word/list/page/dict'],
  'EnglishWords.listEnglishWordVOByPageUsingPOST': ['POST', '/api/english_word/list/page/vo'],
  'EnglishWords.listMyEnglishWordVOByPageUsingPOST': ['POST', '/api/english_word/my/list/page/vo'],
  'EnglishWords.publishWordUsingGET': ['GET', '/api/english_word/publish'],
  'EnglishWords.getScoreEnglishWordUsingGET': ['GET', '/api/english_word/score'],
  'EnglishWords.scoreEnglishWordUsingPOST': ['POST', '/api/english_word/score'],
  'EnglishWords.updateEnglishWordUsingPOST': ['POST', '/api/english_word/update'],
  'englishWordChangeLogController.getEnglishWordChangeLogVOByIdUsingGET': [
    'GET',
    '/api/english_word_change_log/get/vo'
  ],
  'englishWordChangeLogController.listEnglishWordChangeLogByPageUsingPOST': [
    'POST',
    '/api/english_word_change_log/list/page'
  ],
  'englishWordChangeLogController.listEnglishWordChangeLogVOByPageUsingPOST': [
    'POST',
    '/api/english_word_change_log/list/page/vo'
  ],
  'englishWordChangeLogController.listMyEnglishWordChangeLogVOByPageUsingPOST': [
    'POST',
    '/api/english_word_change_log/my/list/page/vo'
  ],
  'examCategoryController.selectOneUsingGET_1': ['GET', '/api/exam_category/selectOne'],
  'examCategoryPaperController.selectOneUsingGET_2': ['GET', '/api/exam_category_paper/selectOne'],
  'examOperationLogController.selectOneUsingGET_3': ['GET', '/api/exam_operation_log/selectOne'],
  'examPaperController.selectOneUsingGET_4': ['GET', '/api/exam_paper/selectOne'],
  'examPaperQuestionController.selectOneUsingGET_5': ['GET', '/api/exam_paper_question/selectOne'],
  'examPaperStatsController.selectOneUsingGET_6': ['GET', '/api/exam_paper_stats/selectOne'],
  'examPaperTagController.selectOneUsingGET_7': ['GET', '/api/exam_paper_tag/selectOne'],
  'examPaperVersionController.selectOneUsingGET_8': ['GET', '/api/exam_paper_version/selectOne'],
  'examQuestionController.selectOneUsingGET_9': ['GET', '/api/exam_question/selectOne'],
  'examTagController.selectOneUsingGET_10': ['GET', '/api/exam_tag/selectOne'],
  'fileController.uploadFileUsingPOST': ['POST', '/api/file/upload'],
  'mediaCreatorController.addMediaCreatorUsingPOST': ['POST', '/api/media_creator/add'],
  'mediaCreatorController.deleteMediaCreatorUsingPOST': ['POST', '/api/media_creator/delete'],
  'mediaCreatorController.getMediaCreatorVOByIdUsingGET': ['GET', '/api/media_creator/get/vo'],
  'mediaCreatorController.listMediaCreatorByPageUsingPOST': ['POST', '/api/media_creator/list/page'],
  'mediaCreatorController.listMediaCreatorVOByPageUsingPOST': ['POST', '/api/media_creator/list/page/vo'],
  'mediaCreatorController.listMyMediaCreatorVOByPageUsingPOST': ['POST', '/api/media_creator/my/list/page/vo'],
  'postController.addPostUsingPOST': ['POST', '/api/post/add'],
  'postController.deletePostUsingPOST': ['POST', '/api/post/delete'],
  'postController.editPostUsingPOST': ['POST', '/api/post/edit'],
  'postController.getPostVOByIdUsingGET': ['GET', '/api/post/get/vo'],
  'postController.listPostByPageUsingPOST': ['POST', '/api/post/list/page'],
  'postController.listPostVOByPageUsingPOST': ['POST', '/api/post/list/page/vo'],
  'postController.listMyPostVOByPageUsingPOST': ['POST', '/api/post/my/list/page/vo'],
  'postController.searchPostVOByPageUsingPOST': ['POST', '/api/post/search/page/vo'],
  'postController.updatePostUsingPOST': ['POST', '/api/post/update'],
  'postFavourController.doPostFavourUsingPOST': ['POST', '/api/post_favour/'],
  'postFavourController.listFavourPostByPageUsingPOST': ['POST', '/api/post_favour/list/page'],
  'postFavourController.listMyFavourPostByPageUsingPOST': ['POST', '/api/post_favour/my/list/page'],
  'postThumbController.doThumbUsingPOST': ['POST', '/api/post_thumb/'],
  'wxMpController.setMenuUsingGET': ['GET', '/api/setMenu'],
  'userController.addUserUsingPOST': ['POST', '/api/user/add'],
  'userController.getDailyQuoteUsingGET': ['GET', '/api/user/dailyquote'],
  'userController.deleteUserUsingPOST': ['POST', '/api/user/delete'],
  'userController.getUserByIdUsingGET': ['GET', '/api/user/get'],
  'userController.getLoginUserUsingGET': ['GET', '/api/user/get/login'],
  'userController.getUserVOByIdUsingGET': ['GET', '/api/user/get/vo'],
  'userController.listUserByPageUsingPOST': ['POST', '/api/user/list/page'],
  'userController.listUserVOByPageUsingPOST': ['POST', '/api/user/list/page/vo'],
  'userController.userLoginTokenUsingPOST': ['POST', '/api/user/login/token'],
  'userController.userLoginByWxOpenUsingGET': ['GET', '/api/user/login/wx_open'],
  'userController.userLogoutUsingPOST': ['POST', '/api/user/logout'],
  'userController.userRegisterUsingPOST': ['POST', '/api/user/register'],
  'userController.updateUserUsingPOST': ['POST', '/api/user/update'],
  'userController.updateMyUserUsingPOST': ['POST', '/api/user/update/my'],
  'userConfigController.getCurrentUserConfigUsingGET': ['GET', '/api/user_config/get'],
  'userConfigController.getPublicUserConfigUsingGET': ['GET', '/api/user_config/public'],
  'userConfigController.selectOneUsingGET_11': ['GET', '/api/user_config/select'],
  'userConfigController.updateCurrentUserConfigUsingPOST': ['POST', '/api/user_config/update'],
  'wordStatusChangeController.listStatusChangeByPageUsingPOST': ['POST', '/api/word_status_change/list/page'],
  'wordStatusChangeController.listRecordUsingGET': ['GET', '/api/word_status_change/list/record'],
  'wordStatusChangeController.selectOneUsingGET_12': ['GET', '/api/word_status_change/selectOne']
};
