apiVersion: oam.coding.net/v1alpha2
kind: ComponentIndex
metadata:
  name: ComponentIndex
spec:
  componentList:
  - createTime: 2024-08-17T09:57:39.895Z
    creatorId: 9152296
    description: 系统内置的Deployment服务模板
    id: 386063390643240
    name: 内置的Deployment服务模板
    seq: DeploymentTemplate
    status: ENABLE
    teamId: 4211598
    type: SERVICE
    updateTime: 2024-08-17T09:57:39.895Z
  - createTime: 2024-08-17T09:57:40.431Z
    creatorId: 9152296
    description: 系统内置的Job服务模板
    id: 386065638790184
    name: 内置的Job服务模板
    seq: JobTemplate
    status: ENABLE
    teamId: 4211598
    type: JOB
    updateTime: 2024-08-17T09:57:40.431Z
  - createTime: 2024-08-17T09:57:40.980Z
    creatorId: 9152296
    description: 系统内置的Deployment服务模板V2
    id: 386067941463080
    name: 内置的Deployment服务模板V2
    seq: DeploymentTemplateV2
    status: ENABLE
    teamId: 4211598
    type: SERVICE
    updateTime: 2024-08-17T09:57:40.980Z
