apiVersion: oam.coding.net/v1alpha1
kind: Trait
metadata:
  annotations:
    name: 禁用灰度
  name: ignore-canary-annotation
spec:
  available: true
  contextVariables:
  - description: 目标对象命名空间
    name: 目标对象命名空间
    required: true
    type: STRING
    variable: namespace
  - description: 目标对象
    name: 目标对象
    required: true
    type: STRING
    variable: src
  - description: 目标对象名称
    name: 目标对象名称
    required: true
    type: STRING
    variable: name
  customVariables: [
    ]
  description: 启用该插件的服务将不会在部署策略中被部署到灰度环境
  strategy: PATCH
  targetGVK:
    apiVersion: apps/v1
    kind: All
  trait:
    apiVersion: apps/v1
    avatar: ignore-canary-annotation
    content: |-
      #运维插件的定义
      #假设运维插件的 id 和 name 都是 ignore-canary-annotation
      # patch 类型的插件，作用对象类型 Deployment
      metadata:
        name: {{.name}}
        namespace: {{.namespace}}
        annotations:
          oam.coding.net/ignore-canary: "true"
    createTime: 2024-08-17T09:57:36.077Z
    creatorId: 9152296
    deleted: false
    description: 启用该插件的服务将不会在部署策略中被部署到灰度环境
    id: 0
    name: 禁用灰度
    pattern: PATCH
    seq: ignore-canary-annotation
    status: ENABLE
    targetType: All
    teamId: 4211598
    updateTime: 2024-08-17T09:57:36.077Z
  traitDefinition:
    kube:
      template: |-
        #运维插件的定义
        #假设运维插件的 id 和 name 都是 ignore-canary-annotation
        # patch 类型的插件，作用对象类型 Deployment
        metadata:
          name: {{.name}}
          namespace: {{.namespace}}
          annotations:
            oam.coding.net/ignore-canary: "true"
