/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/dictionary/[id]': RouteRecordInfo<'/dictionary/[id]', '/dictionary/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/explore/': RouteRecordInfo<'/explore/', '/explore', Record<never, never>, Record<never, never>>,
    '/explore/comprehensive': RouteRecordInfo<'/explore/comprehensive', '/explore/comprehensive', Record<never, never>, Record<never, never>>,
    '/explore/dub': RouteRecordInfo<'/explore/dub', '/explore/dub', Record<never, never>, Record<never, never>>,
    '/explore/listen': RouteRecordInfo<'/explore/listen', '/explore/listen', Record<never, never>, Record<never, never>>,
    '/explore/pronounce': RouteRecordInfo<'/explore/pronounce', '/explore/pronounce', Record<never, never>, Record<never, never>>,
    '/explore/pronounce copy': RouteRecordInfo<'/explore/pronounce copy', '/explore/pronounce copy', Record<never, never>, Record<never, never>>,
    '/explore/pronounce.new': RouteRecordInfo<'/explore/pronounce.new', '/explore/pronounce/new', Record<never, never>, Record<never, never>>,
    '/explore/short-video': RouteRecordInfo<'/explore/short-video', '/explore/short-video', Record<never, never>, Record<never, never>>,
    '/explore/speech': RouteRecordInfo<'/explore/speech', '/explore/speech', Record<never, never>, Record<never, never>>,
    '/old': RouteRecordInfo<'/old', '/old', Record<never, never>, Record<never, never>>,
    '/personal/': RouteRecordInfo<'/personal/', '/personal', Record<never, never>, Record<never, never>>,
    '/personal/develop': RouteRecordInfo<'/personal/develop', '/personal/develop', Record<never, never>, Record<never, never>>,
    '/personal/edit': RouteRecordInfo<'/personal/edit', '/personal/edit', Record<never, never>, Record<never, never>>,
    '/personal/settings': RouteRecordInfo<'/personal/settings', '/personal/settings', Record<never, never>, Record<never, never>>,
    '/personal/theme': RouteRecordInfo<'/personal/theme', '/personal/theme', Record<never, never>, Record<never, never>>,
    '/search': RouteRecordInfo<'/search', '/search', Record<never, never>, Record<never, never>>,
    '/words/': RouteRecordInfo<'/words/', '/words', Record<never, never>, Record<never, never>>,
    '/words/dict-select-page': RouteRecordInfo<'/words/dict-select-page', '/words/dict-select-page', Record<never, never>, Record<never, never>>,
    '/words/dictation': RouteRecordInfo<'/words/dictation', '/words/dictation', Record<never, never>, Record<never, never>>,
    '/words/prewords': RouteRecordInfo<'/words/prewords', '/words/prewords', Record<never, never>, Record<never, never>>,
    '/words/search/[word]': RouteRecordInfo<'/words/search/[word]', '/words/search/:word', { word: ParamValue<true> }, { word: ParamValue<false> }>,
    '/words/signed': RouteRecordInfo<'/words/signed', '/words/signed', Record<never, never>, Record<never, never>>,
  }
}
