/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/chores/dummy': RouteRecordInfo<'/chores/dummy', '/chores/dummy', Record<never, never>, Record<never, never>>,
    '/chores/health': RouteRecordInfo<'/chores/health', '/chores/health', Record<never, never>, Record<never, never>>,
    '/dictionary/[id]': RouteRecordInfo<'/dictionary/[id]', '/dictionary/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/explore/': RouteRecordInfo<'/explore/', '/explore', Record<never, never>, Record<never, never>>,
    '/explore/cet': RouteRecordInfo<'/explore/cet', '/explore/cet', Record<never, never>, Record<never, never>>,
    '/explore/comprehensive': RouteRecordInfo<'/explore/comprehensive', '/explore/comprehensive', Record<never, never>, Record<never, never>>,
    '/explore/dub': RouteRecordInfo<'/explore/dub', '/explore/dub', Record<never, never>, Record<never, never>>,
    '/explore/entertainment': RouteRecordInfo<'/explore/entertainment', '/explore/entertainment', Record<never, never>, Record<never, never>>,
    '/explore/listen': RouteRecordInfo<'/explore/listen', '/explore/listen', Record<never, never>, Record<never, never>>,
    '/explore/poster/': RouteRecordInfo<'/explore/poster/', '/explore/poster', Record<never, never>, Record<never, never>>,
    '/explore/pronounce': RouteRecordInfo<'/explore/pronounce', '/explore/pronounce', Record<never, never>, Record<never, never>>,
    '/explore/pronounce copy': RouteRecordInfo<'/explore/pronounce copy', '/explore/pronounce copy', Record<never, never>, Record<never, never>>,
    '/explore/pronounce.new': RouteRecordInfo<'/explore/pronounce.new', '/explore/pronounce/new', Record<never, never>, Record<never, never>>,
    '/explore/red-typhoon': RouteRecordInfo<'/explore/red-typhoon', '/explore/red-typhoon', Record<never, never>, Record<never, never>>,
    '/explore/short-video': RouteRecordInfo<'/explore/short-video', '/explore/short-video', Record<never, never>, Record<never, never>>,
    '/explore/speech': RouteRecordInfo<'/explore/speech', '/explore/speech', Record<never, never>, Record<never, never>>,
    '/explore/vocabulary-test': RouteRecordInfo<'/explore/vocabulary-test', '/explore/vocabulary-test', Record<never, never>, Record<never, never>>,
    '/explore/word-test': RouteRecordInfo<'/explore/word-test', '/explore/word-test', Record<never, never>, Record<never, never>>,
    '/games/2048/': RouteRecordInfo<'/games/2048/', '/games/2048', Record<never, never>, Record<never, never>>,
    '/games/2048/Block': RouteRecordInfo<'/games/2048/Block', '/games/2048/Block', Record<never, never>, Record<never, never>>,
    '/games/2048/footer/Footer': RouteRecordInfo<'/games/2048/footer/Footer', '/games/2048/footer/Footer', Record<never, never>, Record<never, never>>,
    '/games/2048/footer/FooterButton': RouteRecordInfo<'/games/2048/footer/FooterButton', '/games/2048/footer/FooterButton', Record<never, never>, Record<never, never>>,
    '/games/2048/HeadBar': RouteRecordInfo<'/games/2048/HeadBar', '/games/2048/HeadBar', Record<never, never>, Record<never, never>>,
    '/games/2048/Personal': RouteRecordInfo<'/games/2048/Personal', '/games/2048/Personal', Record<never, never>, Record<never, never>>,
    '/games/2048/rankings/': RouteRecordInfo<'/games/2048/rankings/', '/games/2048/rankings', Record<never, never>, Record<never, never>>,
    '/games/2048/rankings/RankPerson': RouteRecordInfo<'/games/2048/rankings/RankPerson', '/games/2048/rankings/RankPerson', Record<never, never>, Record<never, never>>,
    '/games/2048/Records': RouteRecordInfo<'/games/2048/Records', '/games/2048/Records', Record<never, never>, Record<never, never>>,
    '/games/2048/Settings': RouteRecordInfo<'/games/2048/Settings', '/games/2048/Settings', Record<never, never>, Record<never, never>>,
    '/games/2048/slider/': RouteRecordInfo<'/games/2048/slider/', '/games/2048/slider', Record<never, never>, Record<never, never>>,
    '/games/2048/slider/index_old': RouteRecordInfo<'/games/2048/slider/index_old', '/games/2048/slider/index_old', Record<never, never>, Record<never, never>>,
    '/games/frog/': RouteRecordInfo<'/games/frog/', '/games/frog', Record<never, never>, Record<never, never>>,
    '/games/tang/': RouteRecordInfo<'/games/tang/', '/games/tang', Record<never, never>, Record<never, never>>,
    '/old': RouteRecordInfo<'/old', '/old', Record<never, never>, Record<never, never>>,
    '/personal/': RouteRecordInfo<'/personal/', '/personal', Record<never, never>, Record<never, never>>,
    '/personal/develop': RouteRecordInfo<'/personal/develop', '/personal/develop', Record<never, never>, Record<never, never>>,
    '/personal/edit/': RouteRecordInfo<'/personal/edit/', '/personal/edit', Record<never, never>, Record<never, never>>,
    '/personal/edit/name': RouteRecordInfo<'/personal/edit/name', '/personal/edit/name', Record<never, never>, Record<never, never>>,
    '/personal/settings': RouteRecordInfo<'/personal/settings', '/personal/settings', Record<never, never>, Record<never, never>>,
    '/personal/theme': RouteRecordInfo<'/personal/theme', '/personal/theme', Record<never, never>, Record<never, never>>,
    '/search': RouteRecordInfo<'/search', '/search', Record<never, never>, Record<never, never>>,
    '/test/chat': RouteRecordInfo<'/test/chat', '/test/chat', Record<never, never>, Record<never, never>>,
    '/words/': RouteRecordInfo<'/words/', '/words', Record<never, never>, Record<never, never>>,
    '/words/dict-select-page': RouteRecordInfo<'/words/dict-select-page', '/words/dict-select-page', Record<never, never>, Record<never, never>>,
    '/words/dictation': RouteRecordInfo<'/words/dictation', '/words/dictation', Record<never, never>, Record<never, never>>,
    '/words/prewords': RouteRecordInfo<'/words/prewords', '/words/prewords', Record<never, never>, Record<never, never>>,
    '/words/search/[word]': RouteRecordInfo<'/words/search/[word]', '/words/search/:word', { word: ParamValue<true> }, { word: ParamValue<false> }>,
    '/words/signed': RouteRecordInfo<'/words/signed', '/words/signed', Record<never, never>, Record<never, never>>,
  }
}
