// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  const routes = {"1":{"path":"/user","layout":false,"id":"1"},"2":{"path":"/user/login","parentId":"1","id":"2"},"3":{"path":"/user/register","parentId":"1","id":"3"},"4":{"path":"/welcome","icon":"smile","name":"欢迎页","parentId":"ant-design-pro-layout","id":"4"},"5":{"path":"/admin","icon":"crown","name":"管理页","access":"canAdmin","parentId":"ant-design-pro-layout","id":"5"},"6":{"path":"/admin","redirect":"/admin/user","parentId":"5","id":"6"},"7":{"icon":"table","path":"/admin/user","name":"用户管理","parentId":"5","id":"7"},"8":{"icon":"table","path":"/admin/category","name":"分类管理","parentId":"5","id":"8"},"9":{"icon":"crown","path":"/admin/english","name":"英语管理","access":"canAdmin","parentId":"5","id":"9"},"10":{"icon":"table","path":"/admin/english/dictionary","name":"词典管理","parentId":"9","id":"10"},"11":{"icon":"table","path":"/admin/english/word","name":"单词管理","parentId":"9","id":"11"},"12":{"icon":"table","path":"/admin/english/word-status","name":"单词状态变更统计","parentId":"9","id":"12"},"13":{"icon":"table","path":"/admin/audio","name":"音频管理","parentId":"5","id":"13"},"14":{"icon":"table","path":"/admin/media-creator","name":"AI媒体创作中心","parentId":"5","id":"14"},"15":{"path":"/","redirect":"/welcome","parentId":"ant-design-pro-layout","id":"15"},"16":{"path":"*","layout":false,"id":"16"},"ant-design-pro-layout":{"id":"ant-design-pro-layout","path":"/","isLayout":true},"umi/plugin/openapi":{"path":"/umi/plugin/openapi","id":"umi/plugin/openapi"}} as const;
  return {
    routes,
    routeComponents: {
'1': React.lazy(() => import('./EmptyRoute')),
'2': React.lazy(() => import(/* webpackChunkName: "p__User__Login__index" */'@/pages/User/Login/index.tsx')),
'3': React.lazy(() => import(/* webpackChunkName: "p__User__Register__index" */'@/pages/User/Register/index.tsx')),
'4': React.lazy(() => import(/* webpackChunkName: "p__Welcome" */'@/pages/Welcome.tsx')),
'5': React.lazy(() => import('./EmptyRoute')),
'6': React.lazy(() => import('./EmptyRoute')),
'7': React.lazy(() => import(/* webpackChunkName: "p__Admin__User__index" */'@/pages/Admin/User/index.tsx')),
'8': React.lazy(() => import(/* webpackChunkName: "p__Admin__Category__index" */'@/pages/Admin/Category/index.tsx')),
'9': React.lazy(() => import('./EmptyRoute')),
'10': React.lazy(() => import(/* webpackChunkName: "p__Admin__English__Dictionary__index" */'@/pages/Admin/English/Dictionary/index.tsx')),
'11': React.lazy(() => import(/* webpackChunkName: "p__Admin__English__Word__index" */'@/pages/Admin/English/Word/index.tsx')),
'12': React.lazy(() => import(/* webpackChunkName: "p__Admin__English__WordStatus__index" */'@/pages/Admin/English/WordStatus/index.tsx')),
'13': React.lazy(() => import(/* webpackChunkName: "p__Admin__Audio__index" */'@/pages/Admin/Audio/index.tsx')),
'14': React.lazy(() => import(/* webpackChunkName: "p__Admin__MediaCreator__index" */'@/pages/Admin/MediaCreator/index.tsx')),
'15': React.lazy(() => import('./EmptyRoute')),
'16': React.lazy(() => import(/* webpackChunkName: "p__404" */'@/pages/404.tsx')),
'ant-design-pro-layout': React.lazy(() => import(/* webpackChunkName: "umi__plugin-layout__Layout" */'/Users/talexdreamsoul/WorkSpace/Work/leaves/leaves-word/apps/cms/src/.umi/plugin-layout/Layout.tsx')),
'umi/plugin/openapi': React.lazy(() => import(/* webpackChunkName: "umi__plugin-openapi__openapi" */'/Users/talexdreamsoul/WorkSpace/Work/leaves/leaves-word/apps/cms/src/.umi/plugin-openapi/openapi.tsx')),
},
  };
}
